### ISSUE TITLE
On Clicking Pause randomly , sometime audio player stop working.  

### ISSUE THREAD

**Issue by codevector** [parttio/VaadinAudioPlayer#3]
On Clicking Pause randomly, sometimes the audio player stop working.  it throws an exception offset range exception. 
Attached is 
![audio-playerIssue](https://user-images.githubusercontent.com/2055550/136352889-c9193291-ac88-4b3c-b1cd-9e4226fe457d.png)
the screenshot for the same. 

Steps to reproduce 
1) Select track2.wave to play.
2) Click on Play and then click on pause randomly ( do it fast many times)  

**Expected Result**
The audio player should not stop.
**Actual Result**
Audio Player is stopped working. 
Showing error offset provided (negative value ) less than minimum bound value.

**Comment by codevector** [comment]
Fix for negative offset as follow 

Bold colors lines are the new changes to fix the issue.

Changes in /browser/node_modules/@vaadin/flow-frontend/src/audio-stream-player.js

_Line No,156_
 pause() {
            const scheduleTime = this._getScheduleTime();
            if (this._chunkStartTime !== undefined) {
                const elapsedTime = scheduleTime - this._chunkStartTime;
                this._chunkPosition += elapsedTime * this._playbackSpeed;
                **this._chunkPosition =Math.max(0,this._chunkPosition);**
                this._chunkStartTime = undefined;
            }


_Line No.302_ 
get _currentChunkPosition() {
            let position = this._chunkPosition;
            if (this._chunkStartTime !== undefined) {
                position +=
                    (this._getScheduleTime() - this._chunkStartTime)
                    * this._playbackSpeed;
            }
            **return Math.max(0,position);**
        }

**Comment by jcgueriaud1** [comment]
Thanks for the issue and the solution. It's fixed in version 3.0.1.
